//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OthersEntities : DbContext
    {
        public OthersEntities()
           : base("name=OthersEntities")
          // :base("data source=ANAS-PC;initial catalog=Others;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ElectionCenter> ElectionCenters { get; set; }
        public virtual DbSet<ElectionDepartment> ElectionDepartments { get; set; }
        public virtual DbSet<Elector> Electors { get; set; }
        public virtual DbSet<Governate> Governates { get; set; }
        public virtual DbSet<Municipal> Municipals { get; set; }
    }
}
