//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elector
    {
        public string NationalNo { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string GovernateName { get; set; }
        public string MunicipalName { get; set; }
        public string ElectionDepartmentName { get; set; }
        public string ElectionCenterName { get; set; }
        public string GovernateID { get; set; }
        public string MunicipalID { get; set; }
        public string ElectionDepartmentID { get; set; }
        public string ElectionCenterID { get; set; }
        public Nullable<byte> Age { get; set; }
        public Nullable<bool> Voted { get; set; }
        public Nullable<short> VotedCount { get; set; }
        public byte[] Photo { get; set; }
    }
}
